### ISSUE TITLE
Add api prefix to the paths

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/theta-test-aggregator#77]
On the backend side add api prefix for all of the endpoints. If it's possible group the paths under the api prefix, if not then okay.

Paths examples (just to know what I think):
```
POST localhost:3000/api/user 
GET localhost:3000/api/user
```
Correct me if it's already implemented.
Most kapcsolok, hogy ezt magyarul kellett volna, de nem irom ujra :/

**Comment by GallDavid** [comment]
pont most akartam egy router index.ts-t csinálni :) intézem
